
export const RESPONSE_FETCH_EVENT_REQUEST = "RESPONSE_FETCH_EVENT_REQUEST";
export const RESPONSE_FETCH_EVENT_SUCCESS = "RESPONSE_FETCH_EVENT_SUCCESS";
export const RESPONSE_FETCH_EVENT_FAILURE = "RESPONSE_FETCH_EVENT_FAILURE";
